apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: foyle-cicd
metadata:
  labels:
    environment: dev
resources:
- namespace.yaml
- serviceaccount.yaml
configMapGenerator:
- name: config
  files:
    - config.yaml